services:
  capinde:
    image: ${OPEN_AMBER_CAPINDE_IMAGE:-hentioe/capinde:0.1.0-dev}
    restart: always
    ports:
      - 8080:8080
    environment:
      CAPINDE_HOST: 0.0.0.0
    volumes:
      - ./shared_assets:/out
 