services:
  capinde:
    image: ${OPEN_AMBER_CAPINDE_IMAGE:-hentioe/capinde:0.1.0-dev}
    ports:
      - 8080:8080
    environment:
      CAPINDE_HOST: 0.0.0.0
      CAPINDE_NAMESPACE_BASE: /namespace
      CAPINDE_API_KEY: rpcYUmcu8GukNfHJbUqZWMKbeIrXHtkJpzwYdIeOsdCmZZikO+qEPESaXH6bTSpy
    volumes:
      - ./shared_assets:/namespace/out
 
